### PR TITLE
Add a README linking to the actual document.

### PR DESCRIPTION
**Pull request by tabatkins**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by michaelficarra** [comment]
There's already a link at the top of the repo.

screenshot

Does this actually improve things?

**Comment by rkirsling** [comment]
@michaelficarra Can you edit that text to say ECMA-262 instead of ES262?

**Comment by michaelficarra** [comment]
@rkirsling done

**Comment by tabatkins** [comment]
> There's already a link at the top of the repo.
>
> Does this actually improve things?

I didnt' see that, so observationally: yes, this PR would have helped at least one person (me).

**Pull request merged**
