### PR TITLE
Clarify spec quality requirements as _entrance_ requirements

### PR DESCRIPTION
**Pull request by ljharb**
Hopefully this will smooth over the different interpretations some of us had.

### CODE REVIEW

**Review by bakkot — APPROVED** [review]
wfm

**Review by robpalme — APPROVED** [review]

**Review by gibson042 — APPROVED** [review]

**Review by waldemarhorwat — COMMENTED** [review]
I don't see the existing document being particularly ambiguous. I haven't seen anyone arguing for the interpretation that the Spec Quality column is something that happens later, during the stage, in stages 3 and 4.

The proposed wording makes stage 4 less clear. I'd suggest reverting the changes and instead doing s/Spec Quality/Entrance Spec Quality/ on the column name.

**Comment by ljharb** [comment]
Sure, that works too, will update.

**Review by syg — APPROVED** [review]

**Review by codehag — APPROVED** [review]

**Review by waldemarhorwat — APPROVED** [review]

**Comment by ljharb** [comment]
Announced this in plenary before the lunch break; as there have been no further comments/objections, I'll merge this now.

**Pull request merged**
